# https://blog.deniger.net/post/gitlab-maven-optimize-build/
# https://forum.gitlab.com/t/getting-mvn-release-to-work-with-gitlab-ci/4904/2

# latest: maven:latest
image: maven:3.6.3-jdk-8

# stages
stages:
  - build
  - test
  - release

variables:
  MAVEN_CLI_OPTS: "--batch-mode"
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"

cache:
  paths:
    - .m2/repository/

compile:
  stage: build
  script:
    - mvn $MAVEN_CLI_OPTS compile

test:
  stage: test
  script:
    - mvn $MAVEN_CLI_OPTS test

release:
  stage: release
  tags:
    # runner tags
    - docker
  script:
    # install ssh agent if ssh agent is not installed
    - '(which ssh-agent) || ( apt-get update -y && apt-get install openssh-client -y )'
    # run ssh agent
    - eval $(ssh-agent -s)
    # add the ssh key stored in the SSH_PRIVATE_KEY variable to the ssh agent store
    - ssh-add <(echo "$SSH_PRIVATE_KEY")
    # disable host key check
    - mkdir -p ~/.ssh
    - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
    - git config user.name "jeeto jeeto"
    - git config user.email "jeeto.jeeto@gmail.com"
    # detached HEAD is checked out
    # check out branch in the CI_BUILD_REF_NAME variable
    - git checkout -B "$CI_BUILD_REF_NAME"
    - mvn $MAVEN_CLI_OPTS release:prepare
  artifacts:
    paths:
      - app/target/oboco-*.zip
  when: manual
  only:
     - master